baseurl: "/"
languageCode: "en-us"
defaultContentLanguage: "en"
# defaultContentLanguage: "zh"
title: "Edward Kerman's blog"
theme: "hugo-prose"
googleAnalytics: ""
disqusShortname: ""
ignoreFiles: ["\\.Rmd$", "\\.Rmarkdown$", "_cache$", "\\.knit\\.md$", "\\.utf8\\.md$"]
footnotereturnlinkcontents: "↩"
paginate: 2

permalinks:
  post: "/post/:year/:month/:day/:slug/"

outputs:
  home: [html, rss, json]

# some menu items were added via the `menu` option in YAML in posts
menu:
  header:
    - name: Search
      url: "#"
      identifier: menu-search
    - name: Subscribe
      url: "index.xml"
  footer:
    - name: Categories
      url: "/categories/"
      weight: 1
      pre: "optional"
    - name: Tags
      url: "/tags/"
      weight: 2
      pre: "optional"
    - name: Suggest an edit
      url: "#"
      weight: 3
      identifier: "menu-edit"
    - name: Back to top
      url: "#"

params:
  homePosts: 6
  mainSections: ["post", "work"]
  editLink: "https://github.com/MJ23333/b/edit/master/content/"
  authorDelimiter: " / "
  pageFeatures: [+sidenotes]
  description: >
    A website built through Hugo with the hugo-prose theme.
  footer: >
    &copy; Edward Kerman 2020-2022
    
  license: >
    Text and figures are licensed under [Creative Commons Attribution CC BY
    4.0](https://creativecommons.org/licenses/by/4.0/). 

markup:
  highlight:
    codeFences: false
  goldmark:
    renderer:
      unsafe: true